# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d82d810d18e17b7734f4f1355970df8ac3a4ca6616b59df4ad6f8e209945bb6723925dd6504334fa060ad9c8a31334178b3b6fe4dfb996cc171962ae2cb6392

test:
  secret_key_base: 8fbce626ff1445a9b637776c1a3172710cb37eeca770025438596fbb35c1e64809c04085d2e25109a34979ad286589891aec43904e5d4f33f601a13eae08ec6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
